domain: juju.is

image: prod-comms.ps5.docker-registry.canonical.com/juju.is

extraHosts:
  - domain: conjure-up.io

env:
  - name: SENTRY_DSN
    value: https://a9c1a18b2a0a40bdae6177bb29331a2a@sentry.is.canonical.com//20

  - name: FLASK_GREENHOUSE_API_KEY
    secretKeyRef:
      key: greenhouse_api_key
      name: canonical-com

