domain: juju.is

image: prod-comms.ps5.docker-registry.canonical.com/juju.is

extraHosts:
  - domain: conjure-up.io

env:
  - name: SENTRY_DSN
    value: https://a9c1a18b2a0a40bdae6177bb29331a2a@sentry.is.canonical.com//20

  - name: SEARCH_API_KEY
    secretKeyRef:
      key: google-custom-search-key
      name: google-api

  - name: GREENHOUSE_API_KEY
    secretKeyRef:
      key: greenhouse_api_key
      name: canonical-com

  - name: DISCOURSE_API_KEY
    secretKeyRef:
      key: charmhub-api-key
      name: discourse-api

  - name: DISCOURSE_API_USERNAME
    secretKeyRef:
      key: charmhub-api-username
      name: discourse-api

# Overrides for production
production:
  replicas: 5
  nginxConfigurationSnippet: |
    if ($host != 'juju.is' ) {
      rewrite ^ https://juju.is$request_uri? permanent;
    }
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";

# Overrides for staging
staging:
  replicas: 3
  nginxConfigurationSnippet: |
    if ($host != 'staging.juju.is' ) {
      rewrite ^ https://staging.juju.is$request_uri? permanent;
    }
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
